= Sistema de encriptación

:hardbreaks:
:title-page:
:numbered:
:source-highlighter: coderay
:tabsize: 4

Autores: Maitena_Tamara Escalada_Palma <maitena_escalada@hotmail.com>; v1, {docdate}. 

#Challenge Oracle One

== Descripción
La aplicación lo que hace es encriptar textos, permitiendo intercambiar mensajes secretos 
con otras personas que sepan el secreto de la encriptación utilizada.
El sistema está hecho con HTML, CSS y JavaScript.

Las "llaves" de encriptación que se utilizan son las siguientes:

La letra "e" es convertida para "enter"
La letra "i" es convertida para "imes"
La letra "a" es convertida para "ai"
La letra "o" es convertida para "ober"
La letra "u" es convertida para "ufat"

== Restricciones
- Debe funcionar sólo con letras minúsculas
- No deben ser utilizados letras con acentos ni caracteres especiales
- Debe ser posible convertir una palabra para la versión encriptada también devolver una palabra encriptada para su versión original.

Por ejemplo:
"gato" => "gaitober"
"gaitober" => "gato"
